<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost/sistem1/servers/server.php" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="CheckoutService" targetNamespace="http://localhost/sistem1/servers/server.php">
  <types>
    <xsd:schema targetNamespace="http://localhost/sistem1/servers/server.php">
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </xsd:schema>
  </types>
  <portType name="CheckoutServicePort">
    <operation name="setShippingMethod">
      <documentation>Mengatur metode pengiriman untuk checkout.</documentation>
      <input message="tns:setShippingMethodIn"/>
      <output message="tns:setShippingMethodOut"/>
    </operation>
  </portType>
  <binding name="CheckoutServiceBinding" type="tns:CheckoutServicePort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="setShippingMethod">
      <soap:operation soapAction="http://localhost/sistem1/servers/server.php#setShippingMethod"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/sistem1/servers/server.php"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/sistem1/servers/server.php"/>
      </output>
    </operation>
  </binding>
  <message name="setShippingMethodIn">
    <part name="shippingMethod" type="xsd:string"/>
  </message>
  <message name="setShippingMethodOut">
    <part name="return" type="xsd:string"/>
  </message>
  <service name="CheckoutServiceService">
    <port name="CheckoutServicePort" binding="tns:CheckoutServiceBinding">
      <soap:address location="http://localhost/sistem1/servers/server.php"/>
    </port>
  </service>
</definitions>
